name: ocean-bgc-cookbook-dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - cftime
  - dask
  - dask-jobqueue
  - distributed
  - h5netcdf
  - ipykernel
  - ipywidgets
  - jupyter-book
  - jupyterlab>=3
  - jupyter_server
  - matplotlib
  - metpy
  - nc-time-axis
  - netcdf4
  - numpy
  - pandas
  - pip
  - pop-tools
  - python
  - sphinx-pythia-theme
  - xarray
  - zarr
  - pip
  - pip:
    - s3fs